title: Belkirk College of Engineering
short_title: Belkirk
description: Belkirk Demo Site for Forestry.io
baseurl:
permalink: "/:path/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: noticias
    values:
      layout: noticia
collections:
  people:
    output: true
    permalink: "/en/about/:path"
  posts:
    output: true
    permalink: "/en/posts/:name"
  noticias:
    output: true
    permalink: "/es/noticias/:name"
  carousel_highlights
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
gems:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
