---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: English Content
- type: directory
  path: en/_posts
  label: Posts
  create: documents
  match: "*"
  templates:
  - post
- type: directory
  path: en
  label: Pages
  create: documents
  match: "*.md"
  templates:
  - landing-page
  - default
- type: directory
  path: _people
  label: People
  create: all
  match: "*"
  templates:
  - person
- type: document
  path: _data/information.yml
  label: Contact Information
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
