name: Commit to Trigger Github Pages Publish

on:
  schedule:
  - cron: "0 10 * * 1-5"
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
        with:
          ref: master

      - name: Pull latest
        run: git pull origin master
      - name: Add Git Email
        run: git config --global user.email "jnewcomb125@gmail.com"
      - name: Add Git Username
        run: git config --global user.name "John Newcomb (Github Action)"
      - name: Create empty commit
        run: git commit --allow-empty -m "Trigger notification"
      - name: Push empty commit
        run: git push origin master
