name: Commit to Trigger Github Pages Publish

on:
  schedule:
  - cron: "0 10 * * 1-5"
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Core
        run: npm i @actions/core
      - name: Install Exec
        run: npm i @actions/exec
      - name: Simple commit
        uses: zwaldowski/git-commit-action@v1
        with:
          # Commit message
          commit_message: "Automated message to trigger Gihtub Pages publish"
