name: Commit to Trigger Github Pages Publish

on:
  schedule:
  - cron: "0 10 * * 1-5"
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        run: git checkout master
      - name: Pull latest
        run: git pull origin master
      - name: Create empty commit
        run: git commit --allow-empty -m "Trigger notification"
      - name: Push empty commit
        run: git push origin master
