name: Commit to Trigger Github Pages Publish

on:
  schedule:
  - cron: "0 10 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Jekyll Action
        uses: helaili/jekyll-action@1.0
